export const people =[
    {
        id:1,
        name:'Dilip',
        mail:'Dilip.nadella@gmail.com', 
        link:'https://robohash.org/1'
     },
     {
        id:2,
        name:'Jathin',
        mail:'Jathin.toodi@gmail.com',
        link:'https://robohash.org/2'
     },
     {
        id:3,
        name:'Aastha',
        mail:'Aastha.kumar@gmail.com', 
        link:'https://robohash.org/3'
     },
     {
        id:4,
        name:'Sasi',
        mail:'Sasi.chezerla@gmail.com', 
        link:'https://robohash.org/4'
     },
     {
        id:5,
        name:'pavan',
        mail:'pavan@gmail.com', 
        link:'https://robohash.org/1'
     },
     {
        id:6,
        name:'manish',
        mail:'manish@gmail.com', 
        link:'https://robohash.org/1'
     },
     {
        id:7,
        name:'kranthi',
        mail:'kranthi@gmail.com', 
        link:'https://robohash.org/1'
     },
     {
        id:8,
        name:'suman',
        mail:'suman@gmail.com', 
        link:'https://robohash.org/1'
     },{
        id:9,
        name:'Dilip',
        mail:'Dilip.nadella@gmail.com', 
        link:'https://robohash.org/1'
     },
     {
        id:10,
        name:'Jathin',
        mail:'Jathin.toodi@gmail.com',
        link:'https://robohash.org/2'
     },
     {
        id:11,
        name:'Aastha',
        mail:'Aastha.kumar@gmail.com', 
        link:'https://robohash.org/3'
     },
     {
        id:12,
        name:'Sasi',
        mail:'Sasi.chezerla@gmail.com', 
        link:'https://robohash.org/4'
     },
     {
        id:13,
        name:'pavan',
        mail:'pavan@gmail.com', 
        link:'https://robohash.org/1'
     },
     {
        id:14,
        name:'manish',
        mail:'manish@gmail.com', 
        link:'https://robohash.org/1'
     },
     {
        id:15,
        name:'kranthi',
        mail:'kranthi@gmail.com', 
        link:'https://robohash.org/1'
     },
     {
        id:16,
        name:'suman',
        mail:'suman@gmail.com', 
        link:'https://robohash.org/1'
     },
]